# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# User.create(email: "jp@jp.jp", username: "jp", password: "jpjpjpjp")
# User.create(email: "jt@jt.jt", username: "jt", password: "jtjtjtjt")
# User.create(email: "jb@jb.jb", username: "jb", password: "jbjbjbjb")

# Picture.create(category: "Jordan", url: "1.jpg")
# Picture.create(category: "Kanye Taylor", url: "2.jpg")
# Picture.create(category: "Puppy Horse", url: "3.jpg")
# Picture.create(category: "Usain Bolt", url: "4.jpg")
# Picture.create(category: "Girls", url: "5.jpg")
# Picture.create(category: "Oltean Obama", url: "6.jpg")
# Picture.create(category: "Prince Charles Brazil", url: "7.jpg")
# Picture.create(category: "Rapist Search", url: "8.jpg")
# Picture.create(category: "Smiling Sloth", url: "9.jpg")
# Picture.create(category: "Ghandalf", url: "10.jpg")
# Picture.create(category: "Furry Puppy", url: "11.jpg")
# Picture.create(category: "Batman Thumbs Up", url: "12.jpg")
# Picture.create(category: "Its A Trap", url: "13.jpg")
# Picture.create(category: "Am I The Only One Around Here", url: "14.jpg")
# Picture.create(category: "Creepy Wonka", url: "15.jpg")
# Picture.create(category: "Disaster Girl", url: "16.jpg")
# Picture.create(category: "Surprised Pupper", url: "17.jpg")
# Picture.create(category: "Dr Evil Laser", url: "18.jpg")
# Picture.create(category: "Picard face palm", url: "19.jpg")
# Picture.create(category: "Fry", url: "20.jpg")
# Picture.create(category: "I don't always, but when I do", url: "21.jpg")
# Picture.create(category: "Laundry", url: "22.jpg")
# Picture.create(category: "Mugatu", url: "23.jpg")
# Picture.create(category: "He's so hot right now", url: "24.jpg")
# Picture.create(category: "Obama", url: "25.jpg")
# Picture.create(category: "One Does Not Simply", url: "26.jpg")
# Picture.create(category: "Philosoraptor", url: "27.jpg")
# Picture.create(category: "Picard Angry", url: "28.jpg")
# Picture.create(category: "Yoda", url: "29.jpg")
# Picture.create(category: "Steve Harvery", url: "30.jpg")
# Picture.create(category: "Success Kid", url: "31.jpg")
# Picture.create(category: "Third World Skeptical Kid", url: "32.jpg")
# Picture.create(category: "Third World Success Kid", url: "33.jpg")
# Picture.create(category: "Got any more of that rock", url: "34.jpg")

User.create(email: "arnold@arnold.schwarzenegger", username: "Arnold", password: "arnold12")
User.create(email: "schwarzenegger@schwarzenegger.arnold", username: "Schwarzenegger", password: "arnold12")